server:
  port: 8090
  servlet:
    context-path: /api/statistics
spring:
  application:
    name: kb-statistics

app:
  instance:
    id: ${APP_INSTANCE_ID:}
  datasource:
    url: jdbc:mysql://localhost:3306/kb_document?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: simple
  jackson:
    default-property-inclusion: non_null
