USE kb_foundation;

ALTER TABLE kb_notification
    ADD COLUMN IF NOT EXISTS update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS create_by BIGINT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS update_by BIGINT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS deleted TINYINT NOT NULL DEFAULT 0,
    ADD INDEX IF NOT EXISTS idx_notification_type (notification_type);
